### ISSUE TITLE
'ant jar' doesn't build

### ISSUE THREAD

**Issue by foodpoison** [Gottox/socket.io-java-client#12]
Following the instruction on README, doing 'ant jar' I'm currently getting the following:

```
BUILD FAILED
Target "jar" does not exist in the project "socket.io-java-client". 
```

**Comment by JanisGruzis** [comment]
Im too facing this problem. It would be nice if installation would be a bit more documented.

**Comment by Gottox** [comment]
Hi there!

I'm currently involved in house moving. I try to face this issue at the weekend

@JanisGruzis thanks for your reply, I'll investigate to improve the documentation, too. :)

regards

Enno

**Comment by JanisGruzis** [comment]
I could give a quick fix. I replaced build.xml with older one and changed
some dependencies. (Im new to Java so I may lack the terminology) But it
compiled. Also in installation there should be a comment about changes in
xml. It was pointing to wrong directory of eclipse and those dependencies
may get outdated due to change of eclipse versions. Resume - installation
part asks for a bit detailed explanation (cross OS explanation). But great
work, trying right now to make the magic work. Thanks for your effort.

P.S. added my XML file.

On Thu, Jul 5, 2012 at 5:57 PM, Enno Boland <
reply@reply.github.com

> wrote:
> 
> Hi there!
> 
> I'm currently involved in house moving. I try to face this issue at the
> weekend
> 
> @JanisGruzis thanks for your reply, I'll investigate to improve the
> documentation, too. :)
> 
> regards
> 
> Enno
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/Gottox/socket.io-java-client/issues/12#issuecomment-6780845

## 

Latvijas Universitātes students
Jānis Gruzis

**Comment by Gottox** [comment]
I reverted the commits. Please report any issues about ant. Thank you :D

**Comment by jaydenlin** [comment]
It still has the issue, 

```
$ ant jar
Buildfile: D:\socket.io-java-client\build.xml

BUILD FAILED
Target "jar" does not exist in the project "socket.io-java-client".

Total time: 0 seconds

```

I am using `apache-ant-1.9.2` to build the latest codes and follow the steps from here:
https://github.com/Gottox/socket.io-java-client#how-to-use

```
git clone git://github.com/Gottox/socket.io-java-client.git
cd socket.io-java-client
ant jar
mv jar/socketio.jar /path/to/your/libs/project
```

regards,
Jayden
